version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mediquick_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mediquick
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mediquick_network

  redis:
    image: redis:7.0-alpine
    container_name: mediquick_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mediquick_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mediquick_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/mediquick
      REDIS_HOST: redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mediquick_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mediquick_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - mediquick_network

volumes:
  mongodb_data:
  redis_data:

networks:
  mediquick_network:
    driver: bridge